apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app-of-apps
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/lc2-platform.git
    targetRevision: HEAD
    path: charts/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
